controller:
  enabled: false
scheduling:
  enabled: true

server:
  port: 21106
spring:
  redis:
    port: 6379
    host: r-gs50uhavyclsmv5co6.redis.singapore.rds.aliyuncs.com
    database: 2
    connect-timeout: 5000
    password: R#If4g+1fF2lp-3Dlfl13
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: datasource url
    username: horus_testnet
    password: xxxxxx
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: XCarHikariCP
      max-lifetime: 3600000
      connection-timeout: 60000
      connection-test-query: SELECT 1
      transaction:
        rollback-on-commit-failure: true
      leak-detection-threshold: 3500000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

contracts:
  start: 36115237
  step: 500
  enabled: true
  contractList:
    - name: 'NodePoolFactory' # CreateNodePool
      address: '0x43DcdD76A52ee024FE31E50d51435b9411Ec18FF'
      enabled: true
    - name: 'NodePoolStakingManager' # OperatorBonded
      address: '0x74C8eFc50a56b5cfaDec5E6519787b10554F467a'
      enabled: true
    - name: 'NuLinkStakingSetting'
      address: '0xba1a332fDE6029cccab259c3681E6165910d5293'
      enabled: true
    - name: 'NodePoolRouter'
      address: '0x13a23f40eB6e2EAF0299FE7BAD40F876ecf3F277'
      enabled: true

    - name: 'NodePoolVaultProxy'
      address: '0xe80e4997CD309Fe95Bf94127f5E9D1D156961c56'
      enabled: true

web3j:
  client-address:
    official: https://data-seed-prebsc-1-s1.bnbchain.org:8545
    ankr: https://rpc.ankr.com/bsc_testnet_chapel/1efbffd5898c6a7f6c352cb46bbee1b70535f3f68a6f00594e123a5b30a99daf
    blockpi: https://bsc-testnet.blockpi.network/v1/rpc/f2599ba0b23571e5510fa6e3d34e6d99c64e04a4
  admin-client: true # to manage accounts, enable the admin client
  httpTimeoutSeconds: 60

knife4j:
  enable: true
  setting:
    language: en-US

NULink:
  porter-service-url: http://47.237.117.37:21106
  password: xxxxxx
  chainId: 97
